GET http://localhost:3001/api/numbers

###

DELETE http://localhost:3001/api/numbers/2

###

POST http://localhost:3001/api/numbers/
content-type: application/json

{
    "name": "Kako",
    "number": "1444141414"
}